In [1]:
%load_ext autoreload
%autoreload 2

In [ ]:
import q12
import torch

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int8, device=torch.device("cuda:1"))
x_scale = torch.tensor([1.0], device=torch.device("cuda:1"))
w = torch.tensor([[1, 1], [1, 1], [1, 1]], dtype=torch.int8, device=torch.device("cuda:1"))
w_scale = torch.tensor([1.0, 2.0], device=torch.device("cuda:1"))
bias = torch.tensor([-1, -1], dtype=torch.float16, device=torch.device("cuda:1"))

In [ ]:
q12.matmul_int8_fused(x, x_scale, w, w_scale, bias, per_channel=True)

tensor([[ 5., 11.],
        [14., 29.]], device='cuda:1', dtype=torch.float16)

In [ ]:
None is not None

False

In [ ]:
import q13

In [ ]:
x = torch.tensor([[1, 2], [3, 4], [200, -200]], dtype=torch.float16, device=torch.device("cuda"))
x

tensor([[   1.,    2.],
        [   3.,    4.],
        [ 200., -200.]], device='cuda:0', dtype=torch.float16)

In [34]:
abm, y = q13.quantize_global_transpose(x)
abm.dtype, y.dtype

tensor([0.0050], device='cuda:0')


(torch.int8, torch.float32)